### ISSUE TITLE
GPB: Standards-Based Grading

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#181]
GradingAssignmentScore Object
•New optional element LearningStandardItems
•It’s a list of LearningStandardItem objects
•In the list, the RefId is Mandatory and there are currently no optional elements

**Comment by 4pins** [comment]
List rule used:  LearningStandardItems -> LearningStandardItemList
LearningStandardItemRefIdListType reused!

**Comment by 4pins** [comment]
Help Wanted:
- In the GradingAssignmentScore object, should each LearningStandardItem listed have optional elements like strength and link type?
- Would you find this approach useful for Mark objects? (MarkValueInfo or MarkValue).Or is that redundant with existing relationships to course/section?

**Comment by tqwhite** [comment]
NATB can't answer this. Need assessment domain experts.

**Comment by tqwhite** [comment]
http://specification.sifassociation.org/Implementation/NA/4.3/GradeBookWorkingGroup.html#obj:GradingAssignmentScore

**Comment by 4pins** [comment]
So there is basically two options:
1)  Keep it consistent (clean and simple) with the other Assessment objects (see:  AssessmentItem & AssessmentSubTest).  This is what I ultimately chose to draft.
2)  Keep is consistent (rich and future proof) with GradingAssignmentScore.  This is what the Unity Adoption team told me to do, but I couldn't live with.

Note:  What I drafted also matches every SIF 2 object brought forward at //SIF_Metadata​/EducationFilter​/LearningStandardItems​/LearningStandardItemRefId.

Note:  I am the former Assessment Co-Lead.

**Comment by steve368** [comment]
John, let me pose a hypothetical to help us decide. 
1) Assume the vendors interested in actually working to provide standards-based grades are LMS vendors only. I know that at least ~two~ three of the ~four~ five largest LMS vendors want to provide standards-based grades. At this point, I don't know of any assessment vendors that want to provide standards-based grades soon, and I don't believe there are any. If you have information to the contrary I'd love to hear it.
2) Assume the programmer at the LMS vendor isn't the one who wrote any previous grade passback code. (Most major vendors in our industry have ridiculously high turnover -- not in employment status but in project assignments.)  
3) Assume the programmer knows REST and US K12 data but doesn't know SIF.

*First hypothetical:* Will this programmer find it takes less time, more time, or about the same to implement grade passback using the Assessment-oriented approach instead of the Adoption committee's requested approach?
*Second hypothetical:* The programmer's identical twin works for a SIS vendor. Same experience and same question from the subscriber/SIS/gradebook perspective.

**Comment by 4pins** [comment]
So an important note:  GradingAssignmentScore is not an Assessment object, it is a Grade Book object.  While Assessments (all the way down to the Item level) are usually designed to check specific Learning Standards, Assignments often aren't and get tagged later.  This makes it far more likely that Strength and Link Type fields are desirable!

So a less important note:  Since GradingAssignmentScore already has //SIF_Metadata​/EducationFilter​/LearningStandardItems​/LearningStandardItemRefId a richer structure might cause our messaging about Standards Based Grading being enhanced to be better received.

If you can't tell, I am leaning towards, "Steve was right."

**Comment by 4pins** [comment]
The NATB just decided, "Steve was right."  I will change in the next draft.

**Comment by 4pins** [comment]
Went back to Steve's slides and I believe I have honored them properly in both GradingAssignment and GradingAssignmentScore objects.

**Comment by 4pins** [comment]
Normative changes were indeed made in NADM 4.3.  Guidance document in first draft.  Closing ticket!
