### ISSUE TITLE
Add ApprovedGrades to SchoolInfo?

### ISSUE THREAD

**Issue by 4pins** [Access4LearningNA/specgen_input_na#35]
NCDPI stores both the current grade levels offered at a school as well as the grades the school is approved to enroll students. There is no current SIF element to collect the grades a school is approved to offer.

See:  https://github.com/CEDStandards/CEDS-Elements/issues/25

**Comment by 4pins** [comment]
Please add and map right after GradeLevels (in SchoolInfo).

https://ceds.ed.gov/element/001926

**Comment by 4pins** [comment]
This is my draft:
![Screen Shot 2021-05-21 at 12 25 05 PM](https://user-images.githubusercontent.com/10967355/119188579-af2b1e80-ba2f-11eb-9af6-d28fc5037d3e.png)
![Screen Shot 2021-05-21 at 12 25 34 PM](https://user-images.githubusercontent.com/10967355/119188588-b18d7880-ba2f-11eb-9e21-4b4bad4dc2bd.png)

**Comment by 4pins** [comment]
Redo (still code structure)!
GradeLevelsApprovedList
GradeLevelApproved (map to CEDS 001926)

**Comment by 4pins** [comment]
Note:  Reconciled the 's' in GradeLevelsApproved
Good?
![Screen Shot 2021-07-16 at 2 18 23 PM](https://user-images.githubusercontent.com/10967355/126009507-c861b560-e62b-4d57-ac1f-488a7ea33d34.png)

**Comment by 4pins** [comment]
NATB's initial take is that NC should consider:
- Counting the Students (per grade)
- Counting the Teachers (per grade)
- An extended element

I will dig into CEDS 9 further.

**Comment by johnmannpaul** [comment]
WY has the following use case for this:

School X in District Y is configured to teach grades 3-5 for the year and the window of time for reconfiguration has passed. Sometime later the district decides to offer a joint 2nd and 3rd grade classroom at school X because there are too many 2nd graders at school Z and too few 3rd graders at school X, and the new class appears to solve the overflow/shortfall the District is experiencing. The State advises District Y that they can't fund them for the 2nd graders at School X since they fall outside of the approved configuration (i.e. that's the law). District Y proceeds anyway and has second graders at School X all year.

The approved or funded grades (3-5) need to be reported separately from the actual grades (2-5).

**Comment by 4pins** [comment]
Rather than a parallel list, how about adding a status to the GradeLevel type?

**Comment by johnmannpaul** [comment]
This seems like it would work if it could be assumed that the approved grades will be a subset of the grades offered, but it appears that in the NC use case of a charter school potentially offering fewer grades than they have been approved for, the opposite would be the case (i.e. the offered grades are a strict subset of the approved grades). Final conclusion is that both lists are probably warranted as originally proposed.

**Comment by 4pins** [comment]
So I am recommending keeping the parallel structure.

One refinement in two places:
GradeLevelsApprovedList -> GradeLevelApprovedList
GradeLevelsApproved -> GradeLevelApproved

**Comment by ajackl** [comment]
Object Referenced in this Ticket (we are adding an "ApprovedGradeLevels" type to distinguish what the  School is authorized to teach versus what they do teach.  Could be less than the approved  list or beyond it, or just different:
http://specification.sifassociation.org/Implementation/NA/4.3/StudentInformationSystemsWorkingGroup.html#obj:SchoolInfo

**Comment by ajackl** [comment]
NATB Approved

**Comment by 4pins** [comment]
Confirmed in release.

Closing.
